// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ro.alex.client.managed.ui.desktop;
import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.SpanElement;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import ro.alex.client.managed.ui.AbonamentDetailsView;
import ro.alex.client.proxy.AbonamentProxy;
import ro.alex.client.scaffold.place.ProxyListView;

public abstract class AbonamentDesktopDetailsView_Roo_Gwt extends Composite implements AbonamentDetailsView {

    @UiField
    SpanElement id;

    @UiField
    SpanElement serie;

    @UiField
    SpanElement kilometri;

    @UiField
    SpanElement cost;

    @UiField
    SpanElement version;

    AbonamentProxy proxy;

    @UiField
    SpanElement displayRenderer;

    public void setValue(AbonamentProxy proxy) {
        this.proxy = proxy;
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        serie.setInnerText(proxy.getSerie() == null ? "" : String.valueOf(proxy.getSerie()));
        kilometri.setInnerText(proxy.getKilometri() == null ? "" : String.valueOf(proxy.getKilometri()));
        cost.setInnerText(proxy.getCost() == null ? "" : String.valueOf(proxy.getCost()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
        displayRenderer.setInnerText(ro.alex.client.managed.ui.renderer.AbonamentProxyRenderer.instance().render(proxy));
    }
}
