// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ro.alex.client.managed.ui.desktop;
import com.google.gwt.core.client.GWT;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.text.client.DateTimeFormatRenderer;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.text.shared.Renderer;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.user.cellview.client.CellTable;
import com.google.gwt.user.cellview.client.HasKeyboardSelectionPolicy.KeyboardSelectionPolicy;
import com.google.gwt.user.cellview.client.TextColumn;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.HTMLPanel;
import java.util.HashSet;
import java.util.Set;
import ro.alex.client.proxy.AvionProxy;
import ro.alex.client.proxy.ClasaProxy;
import ro.alex.client.proxy.LocProxy;
import ro.alex.client.proxy.ZborProxy;
import ro.alex.client.scaffold.place.AbstractProxyListView;

public abstract class LocDesktopListView_Roo_Gwt extends AbstractProxyListView<LocProxy> {

    @UiField
    CellTable<LocProxy> table;

    protected Set<String> paths = new HashSet<String>();

    public void init() {
        paths.add("id");
        table.addColumn(new TextColumn<LocProxy>() {

            Renderer<java.lang.Long> renderer = new AbstractRenderer<java.lang.Long>() {

                public String render(java.lang.Long obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(LocProxy object) {
                return renderer.render(object.getId());
            }
        }, "Id");
        paths.add("numar");
        table.addColumn(new TextColumn<LocProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(LocProxy object) {
                return renderer.render(object.getNumar());
            }
        }, "Numar");
        paths.add("clasa");
        table.addColumn(new TextColumn<LocProxy>() {

            Renderer<ro.alex.client.proxy.ClasaProxy> renderer = ro.alex.client.managed.ui.renderer.ClasaProxyRenderer.instance();

            @Override
            public String getValue(LocProxy object) {
                return renderer.render(object.getClasa());
            }
        }, "Clasa");
        paths.add("avion");
        table.addColumn(new TextColumn<LocProxy>() {

            Renderer<ro.alex.client.proxy.AvionProxy> renderer = ro.alex.client.managed.ui.renderer.AvionProxyRenderer.instance();

            @Override
            public String getValue(LocProxy object) {
                return renderer.render(object.getAvion());
            }
        }, "Avion");
        paths.add("zbor");
        table.addColumn(new TextColumn<LocProxy>() {

            Renderer<ro.alex.client.proxy.ZborProxy> renderer = ro.alex.client.managed.ui.renderer.ZborProxyRenderer.instance();

            @Override
            public String getValue(LocProxy object) {
                return renderer.render(object.getZbor());
            }
        }, "Zbor");
        paths.add("ocupat");
        table.addColumn(new TextColumn<LocProxy>() {

            Renderer<java.lang.Boolean> renderer = new AbstractRenderer<java.lang.Boolean>() {

                public String render(java.lang.Boolean obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(LocProxy object) {
                return renderer.render(object.getOcupat());
            }
        }, "Ocupat");
        paths.add("version");
        table.addColumn(new TextColumn<LocProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(LocProxy object) {
                return renderer.render(object.getVersion());
            }
        }, "Version");
    }
}
