// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ro.alex.client.managed.ui.desktop;
import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.SpanElement;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import ro.alex.client.managed.ui.OrasDetailsView;
import ro.alex.client.proxy.OrasProxy;
import ro.alex.client.scaffold.place.ProxyListView;

public abstract class OrasDesktopDetailsView_Roo_Gwt extends Composite implements OrasDetailsView {

    @UiField
    SpanElement id;

    @UiField
    SpanElement denumire;

    @UiField
    SpanElement version;

    OrasProxy proxy;

    @UiField
    SpanElement displayRenderer;

    public void setValue(OrasProxy proxy) {
        this.proxy = proxy;
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        denumire.setInnerText(proxy.getDenumire() == null ? "" : String.valueOf(proxy.getDenumire()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
        displayRenderer.setInnerText(ro.alex.client.managed.ui.renderer.OrasProxyRenderer.instance().render(proxy));
    }
}
