// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ro.alex.client.managed.ui.desktop;
import com.google.gwt.core.client.GWT;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.text.client.DateTimeFormatRenderer;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.text.shared.Renderer;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.user.cellview.client.CellTable;
import com.google.gwt.user.cellview.client.HasKeyboardSelectionPolicy.KeyboardSelectionPolicy;
import com.google.gwt.user.cellview.client.TextColumn;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.HTMLPanel;
import java.util.HashSet;
import java.util.Set;
import ro.alex.client.proxy.LocProxy;
import ro.alex.client.proxy.PersoanaProxy;
import ro.alex.client.proxy.RezervareProxy;
import ro.alex.client.proxy.ZborProxy;
import ro.alex.client.scaffold.place.AbstractProxyListView;

public abstract class RezervareDesktopListView_Roo_Gwt extends AbstractProxyListView<RezervareProxy> {

    @UiField
    CellTable<RezervareProxy> table;

    protected Set<String> paths = new HashSet<String>();

    public void init() {
        paths.add("id");
        table.addColumn(new TextColumn<RezervareProxy>() {

            Renderer<java.lang.Long> renderer = new AbstractRenderer<java.lang.Long>() {

                public String render(java.lang.Long obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(RezervareProxy object) {
                return renderer.render(object.getId());
            }
        }, "Id");
        paths.add("cost");
        table.addColumn(new TextColumn<RezervareProxy>() {

            Renderer<java.lang.Double> renderer = new AbstractRenderer<java.lang.Double>() {

                public String render(java.lang.Double obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(RezervareProxy object) {
                return renderer.render(object.getCost());
            }
        }, "Cost");
        paths.add("locDus");
        table.addColumn(new TextColumn<RezervareProxy>() {

            Renderer<ro.alex.client.proxy.LocProxy> renderer = ro.alex.client.managed.ui.renderer.LocProxyRenderer.instance();

            @Override
            public String getValue(RezervareProxy object) {
                return renderer.render(object.getLocDus());
            }
        }, "Loc Dus");
        paths.add("locIntors");
        table.addColumn(new TextColumn<RezervareProxy>() {

            Renderer<ro.alex.client.proxy.LocProxy> renderer = ro.alex.client.managed.ui.renderer.LocProxyRenderer.instance();

            @Override
            public String getValue(RezervareProxy object) {
                return renderer.render(object.getLocIntors());
            }
        }, "Loc Intors");
        paths.add("nume");
        table.addColumn(new TextColumn<RezervareProxy>() {

            Renderer<java.lang.String> renderer = new AbstractRenderer<java.lang.String>() {

                public String render(java.lang.String obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(RezervareProxy object) {
                return renderer.render(object.getNume());
            }
        }, "Nume");
        paths.add("prenume");
        table.addColumn(new TextColumn<RezervareProxy>() {

            Renderer<java.lang.String> renderer = new AbstractRenderer<java.lang.String>() {

                public String render(java.lang.String obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(RezervareProxy object) {
                return renderer.render(object.getPrenume());
            }
        }, "Prenume");
        paths.add("cod");
        table.addColumn(new TextColumn<RezervareProxy>() {

            Renderer<java.lang.String> renderer = new AbstractRenderer<java.lang.String>() {

                public String render(java.lang.String obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(RezervareProxy object) {
                return renderer.render(object.getCod());
            }
        }, "Cod");
        paths.add("zborDus");
        table.addColumn(new TextColumn<RezervareProxy>() {

            Renderer<ro.alex.client.proxy.ZborProxy> renderer = ro.alex.client.managed.ui.renderer.ZborProxyRenderer.instance();

            @Override
            public String getValue(RezervareProxy object) {
                return renderer.render(object.getZborDus());
            }
        }, "Zbor Dus");
        paths.add("zborIntors");
        table.addColumn(new TextColumn<RezervareProxy>() {

            Renderer<ro.alex.client.proxy.ZborProxy> renderer = ro.alex.client.managed.ui.renderer.ZborProxyRenderer.instance();

            @Override
            public String getValue(RezervareProxy object) {
                return renderer.render(object.getZborIntors());
            }
        }, "Zbor Intors");
        paths.add("persoana");
        table.addColumn(new TextColumn<RezervareProxy>() {

            Renderer<ro.alex.client.proxy.PersoanaProxy> renderer = ro.alex.client.managed.ui.renderer.PersoanaProxyRenderer.instance();

            @Override
            public String getValue(RezervareProxy object) {
                return renderer.render(object.getPersoana());
            }
        }, "Persoana");
        paths.add("dusIntors");
        table.addColumn(new TextColumn<RezervareProxy>() {

            Renderer<java.lang.Boolean> renderer = new AbstractRenderer<java.lang.Boolean>() {

                public String render(java.lang.Boolean obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(RezervareProxy object) {
                return renderer.render(object.getDusIntors());
            }
        }, "Dus Intors");
        paths.add("version");
        table.addColumn(new TextColumn<RezervareProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(RezervareProxy object) {
                return renderer.render(object.getVersion());
            }
        }, "Version");
    }
}
