// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ro.alex.client.managed.ui.desktop;
import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.SpanElement;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import ro.alex.client.managed.ui.UserDetailsView;
import ro.alex.client.proxy.UserProxy;
import ro.alex.client.scaffold.place.ProxyListView;

public abstract class UserDesktopDetailsView_Roo_Gwt extends Composite implements UserDetailsView {

    @UiField
    SpanElement id;

    @UiField
    SpanElement nick;

    @UiField
    SpanElement parola;

    @UiField
    SpanElement version;

    UserProxy proxy;

    @UiField
    SpanElement displayRenderer;

    public void setValue(UserProxy proxy) {
        this.proxy = proxy;
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        nick.setInnerText(proxy.getNick() == null ? "" : String.valueOf(proxy.getNick()));
        parola.setInnerText(proxy.getParola() == null ? "" : String.valueOf(proxy.getParola()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
        displayRenderer.setInnerText(ro.alex.client.managed.ui.renderer.UserProxyRenderer.instance().render(proxy));
    }
}
