// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ro.alex.client.managed.activity;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import ro.alex.client.managed.request.ApplicationRequestFactory;
import ro.alex.client.managed.ui.desktop.AeroportDesktopDetailsView;
import ro.alex.client.managed.ui.desktop.AeroportDesktopEditView;
import ro.alex.client.managed.ui.desktop.AeroportDesktopListView;
import ro.alex.client.managed.ui.mobile.AeroportMobileDetailsView;
import ro.alex.client.managed.ui.mobile.AeroportMobileEditView;
import ro.alex.client.proxy.AeroportProxy;
import ro.alex.client.request.AeroportRequest;
import ro.alex.client.scaffold.ScaffoldApp;
import ro.alex.client.scaffold.place.ProxyPlace;

public abstract class AeroportActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory factory;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        AeroportDesktopEditView.instance().setCreating(true);
        Activity activity = new AeroportEditActivity(null, factory, ScaffoldApp.isMobile() ? AeroportMobileEditView.instance() : AeroportDesktopEditView.instance(), placeController);
        return new AeroportEditActivityWrapper(factory, ScaffoldApp.isMobile() ? AeroportMobileEditView.instance() : AeroportDesktopEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<AeroportProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<AeroportProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        AeroportDesktopEditView.instance().setCreating(false);
        EntityProxyId<AeroportProxy> proxyId = coerceId(place);
        Activity activity = new AeroportEditActivity(proxyId, factory, ScaffoldApp.isMobile() ? AeroportMobileEditView.instance() : AeroportDesktopEditView.instance(), placeController);
        return new AeroportEditActivityWrapper(factory, ScaffoldApp.isMobile() ? AeroportMobileEditView.instance() : AeroportDesktopEditView.instance(), activity, proxyId);
    }
}
