// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ro.alex.client.managed.activity;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import ro.alex.client.managed.request.ApplicationRequestFactory;
import ro.alex.client.managed.ui.desktop.ClasaDesktopDetailsView;
import ro.alex.client.managed.ui.desktop.ClasaDesktopEditView;
import ro.alex.client.managed.ui.desktop.ClasaDesktopListView;
import ro.alex.client.managed.ui.mobile.ClasaMobileDetailsView;
import ro.alex.client.managed.ui.mobile.ClasaMobileEditView;
import ro.alex.client.proxy.ClasaProxy;
import ro.alex.client.request.ClasaRequest;
import ro.alex.client.scaffold.ScaffoldApp;
import ro.alex.client.scaffold.place.ProxyPlace;

public abstract class ClasaActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory factory;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        ClasaDesktopEditView.instance().setCreating(true);
        Activity activity = new ClasaEditActivity(null, factory, ScaffoldApp.isMobile() ? ClasaMobileEditView.instance() : ClasaDesktopEditView.instance(), placeController);
        return new ClasaEditActivityWrapper(factory, ScaffoldApp.isMobile() ? ClasaMobileEditView.instance() : ClasaDesktopEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<ClasaProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<ClasaProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        ClasaDesktopEditView.instance().setCreating(false);
        EntityProxyId<ClasaProxy> proxyId = coerceId(place);
        Activity activity = new ClasaEditActivity(proxyId, factory, ScaffoldApp.isMobile() ? ClasaMobileEditView.instance() : ClasaDesktopEditView.instance(), placeController);
        return new ClasaEditActivityWrapper(factory, ScaffoldApp.isMobile() ? ClasaMobileEditView.instance() : ClasaDesktopEditView.instance(), activity, proxyId);
    }
}
