// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ro.alex.client.managed.activity;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import ro.alex.client.managed.request.ApplicationRequestFactory;
import ro.alex.client.managed.ui.desktop.CompanieDesktopDetailsView;
import ro.alex.client.managed.ui.desktop.CompanieDesktopEditView;
import ro.alex.client.managed.ui.desktop.CompanieDesktopListView;
import ro.alex.client.managed.ui.mobile.CompanieMobileDetailsView;
import ro.alex.client.managed.ui.mobile.CompanieMobileEditView;
import ro.alex.client.proxy.CompanieProxy;
import ro.alex.client.request.CompanieRequest;
import ro.alex.client.scaffold.ScaffoldApp;
import ro.alex.client.scaffold.place.ProxyPlace;

public abstract class CompanieActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory factory;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        CompanieDesktopEditView.instance().setCreating(true);
        Activity activity = new CompanieEditActivity(null, factory, ScaffoldApp.isMobile() ? CompanieMobileEditView.instance() : CompanieDesktopEditView.instance(), placeController);
        return new CompanieEditActivityWrapper(factory, ScaffoldApp.isMobile() ? CompanieMobileEditView.instance() : CompanieDesktopEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<CompanieProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<CompanieProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        CompanieDesktopEditView.instance().setCreating(false);
        EntityProxyId<CompanieProxy> proxyId = coerceId(place);
        Activity activity = new CompanieEditActivity(proxyId, factory, ScaffoldApp.isMobile() ? CompanieMobileEditView.instance() : CompanieDesktopEditView.instance(), placeController);
        return new CompanieEditActivityWrapper(factory, ScaffoldApp.isMobile() ? CompanieMobileEditView.instance() : CompanieDesktopEditView.instance(), activity, proxyId);
    }
}
