// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ro.alex.client.managed.activity;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import ro.alex.client.managed.request.ApplicationRequestFactory;
import ro.alex.client.managed.ui.desktop.ContDesktopDetailsView;
import ro.alex.client.managed.ui.desktop.ContDesktopEditView;
import ro.alex.client.managed.ui.desktop.ContDesktopListView;
import ro.alex.client.managed.ui.mobile.ContMobileDetailsView;
import ro.alex.client.managed.ui.mobile.ContMobileEditView;
import ro.alex.client.proxy.ContProxy;
import ro.alex.client.request.ContRequest;
import ro.alex.client.scaffold.ScaffoldApp;
import ro.alex.client.scaffold.place.ProxyPlace;

public abstract class ContActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory factory;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        ContDesktopEditView.instance().setCreating(true);
        Activity activity = new ContEditActivity(null, factory, ScaffoldApp.isMobile() ? ContMobileEditView.instance() : ContDesktopEditView.instance(), placeController);
        return new ContEditActivityWrapper(factory, ScaffoldApp.isMobile() ? ContMobileEditView.instance() : ContDesktopEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<ContProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<ContProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        ContDesktopEditView.instance().setCreating(false);
        EntityProxyId<ContProxy> proxyId = coerceId(place);
        Activity activity = new ContEditActivity(proxyId, factory, ScaffoldApp.isMobile() ? ContMobileEditView.instance() : ContDesktopEditView.instance(), placeController);
        return new ContEditActivityWrapper(factory, ScaffoldApp.isMobile() ? ContMobileEditView.instance() : ContDesktopEditView.instance(), activity, proxyId);
    }
}
