// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ro.alex.client.managed.activity;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import ro.alex.client.managed.request.ApplicationRequestFactory;
import ro.alex.client.managed.ui.desktop.LocDesktopDetailsView;
import ro.alex.client.managed.ui.desktop.LocDesktopEditView;
import ro.alex.client.managed.ui.desktop.LocDesktopListView;
import ro.alex.client.managed.ui.mobile.LocMobileDetailsView;
import ro.alex.client.managed.ui.mobile.LocMobileEditView;
import ro.alex.client.proxy.AvionProxy;
import ro.alex.client.proxy.ClasaProxy;
import ro.alex.client.proxy.LocProxy;
import ro.alex.client.proxy.ZborProxy;
import ro.alex.client.request.LocRequest;
import ro.alex.client.scaffold.ScaffoldApp;
import ro.alex.client.scaffold.place.ProxyPlace;

public abstract class LocActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory factory;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        LocDesktopEditView.instance().setCreating(true);
        Activity activity = new LocEditActivity(null, factory, ScaffoldApp.isMobile() ? LocMobileEditView.instance() : LocDesktopEditView.instance(), placeController);
        return new LocEditActivityWrapper(factory, ScaffoldApp.isMobile() ? LocMobileEditView.instance() : LocDesktopEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<LocProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<LocProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        LocDesktopEditView.instance().setCreating(false);
        EntityProxyId<LocProxy> proxyId = coerceId(place);
        Activity activity = new LocEditActivity(proxyId, factory, ScaffoldApp.isMobile() ? LocMobileEditView.instance() : LocDesktopEditView.instance(), placeController);
        return new LocEditActivityWrapper(factory, ScaffoldApp.isMobile() ? LocMobileEditView.instance() : LocDesktopEditView.instance(), activity, proxyId);
    }
}
