// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ro.alex.client.managed.activity;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import ro.alex.client.managed.request.ApplicationRequestFactory;
import ro.alex.client.managed.ui.desktop.PersoanaDesktopDetailsView;
import ro.alex.client.managed.ui.desktop.PersoanaDesktopEditView;
import ro.alex.client.managed.ui.desktop.PersoanaDesktopListView;
import ro.alex.client.managed.ui.mobile.PersoanaMobileDetailsView;
import ro.alex.client.managed.ui.mobile.PersoanaMobileEditView;
import ro.alex.client.proxy.AbonamentProxy;
import ro.alex.client.proxy.PersoanaProxy;
import ro.alex.client.proxy.UserProxy;
import ro.alex.client.request.PersoanaRequest;
import ro.alex.client.scaffold.ScaffoldApp;
import ro.alex.client.scaffold.place.ProxyPlace;

public abstract class PersoanaActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory factory;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        PersoanaDesktopEditView.instance().setCreating(true);
        Activity activity = new PersoanaEditActivity(null, factory, ScaffoldApp.isMobile() ? PersoanaMobileEditView.instance() : PersoanaDesktopEditView.instance(), placeController);
        return new PersoanaEditActivityWrapper(factory, ScaffoldApp.isMobile() ? PersoanaMobileEditView.instance() : PersoanaDesktopEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<PersoanaProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<PersoanaProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        PersoanaDesktopEditView.instance().setCreating(false);
        EntityProxyId<PersoanaProxy> proxyId = coerceId(place);
        Activity activity = new PersoanaEditActivity(proxyId, factory, ScaffoldApp.isMobile() ? PersoanaMobileEditView.instance() : PersoanaDesktopEditView.instance(), placeController);
        return new PersoanaEditActivityWrapper(factory, ScaffoldApp.isMobile() ? PersoanaMobileEditView.instance() : PersoanaDesktopEditView.instance(), activity, proxyId);
    }
}
