// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ro.alex.client.managed.activity;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.place.shared.Place;
import com.google.gwt.user.client.ui.AcceptsOneWidget;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.Receiver;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import ro.alex.client.managed.activity.PersoanaEditActivityWrapper.View;
import ro.alex.client.managed.request.ApplicationRequestFactory;
import ro.alex.client.managed.ui.PersoanaEditView;
import ro.alex.client.proxy.AbonamentProxy;
import ro.alex.client.proxy.PersoanaProxy;
import ro.alex.client.proxy.UserProxy;
import ro.alex.client.scaffold.activity.IsScaffoldMobileActivity;
import ro.alex.client.scaffold.place.ProxyEditView;
import ro.alex.client.scaffold.place.ProxyListPlace;
import ro.alex.client.scaffold.place.ProxyPlace;

public abstract class PersoanaEditActivityWrapper_Roo_Gwt implements Activity, IsScaffoldMobileActivity {

    protected Activity wrapped;

    protected View<?> view;

    protected ApplicationRequestFactory requests;

    @Override
    public void start(AcceptsOneWidget display, EventBus eventBus) {
        view.setUserPickerValues(Collections.<UserProxy>emptyList());
        requests.userRequest().findUserEntries(0, 50).with(ro.alex.client.managed.ui.renderer.UserProxyRenderer.instance().getPaths()).fire(new Receiver<List<UserProxy>>() {

            public void onSuccess(List<UserProxy> response) {
                List<UserProxy> values = new ArrayList<UserProxy>();
                values.add(null);
                values.addAll(response);
                view.setUserPickerValues(values);
            }
        });
        view.setAbonamentPickerValues(Collections.<AbonamentProxy>emptyList());
        requests.abonamentRequest().findAbonamentEntries(0, 50).with(ro.alex.client.managed.ui.renderer.AbonamentProxyRenderer.instance().getPaths()).fire(new Receiver<List<AbonamentProxy>>() {

            public void onSuccess(List<AbonamentProxy> response) {
                List<AbonamentProxy> values = new ArrayList<AbonamentProxy>();
                values.add(null);
                values.addAll(response);
                view.setAbonamentPickerValues(values);
            }
        });
        wrapped.start(display, eventBus);
    }

    public interface View_Roo_Gwt<V extends ro.alex.client.managed.ui.PersoanaEditView<V>> extends PersoanaEditView<V> {

        void setUserPickerValues(Collection<UserProxy> values);

        void setAbonamentPickerValues(Collection<AbonamentProxy> values);
    }
}
