// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ro.alex.client.managed.activity;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import ro.alex.client.managed.request.ApplicationRequestFactory;
import ro.alex.client.managed.ui.desktop.RezervareDesktopDetailsView;
import ro.alex.client.managed.ui.desktop.RezervareDesktopEditView;
import ro.alex.client.managed.ui.desktop.RezervareDesktopListView;
import ro.alex.client.managed.ui.mobile.RezervareMobileDetailsView;
import ro.alex.client.managed.ui.mobile.RezervareMobileEditView;
import ro.alex.client.proxy.LocProxy;
import ro.alex.client.proxy.PersoanaProxy;
import ro.alex.client.proxy.RezervareProxy;
import ro.alex.client.proxy.ZborProxy;
import ro.alex.client.request.RezervareRequest;
import ro.alex.client.scaffold.ScaffoldApp;
import ro.alex.client.scaffold.place.ProxyPlace;

public abstract class RezervareActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory factory;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        RezervareDesktopEditView.instance().setCreating(true);
        Activity activity = new RezervareEditActivity(null, factory, ScaffoldApp.isMobile() ? RezervareMobileEditView.instance() : RezervareDesktopEditView.instance(), placeController);
        return new RezervareEditActivityWrapper(factory, ScaffoldApp.isMobile() ? RezervareMobileEditView.instance() : RezervareDesktopEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<RezervareProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<RezervareProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        RezervareDesktopEditView.instance().setCreating(false);
        EntityProxyId<RezervareProxy> proxyId = coerceId(place);
        Activity activity = new RezervareEditActivity(proxyId, factory, ScaffoldApp.isMobile() ? RezervareMobileEditView.instance() : RezervareDesktopEditView.instance(), placeController);
        return new RezervareEditActivityWrapper(factory, ScaffoldApp.isMobile() ? RezervareMobileEditView.instance() : RezervareDesktopEditView.instance(), activity, proxyId);
    }
}
