// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ro.alex.client.managed.activity;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import ro.alex.client.managed.request.ApplicationRequestFactory;
import ro.alex.client.managed.ui.desktop.ZborDesktopDetailsView;
import ro.alex.client.managed.ui.desktop.ZborDesktopEditView;
import ro.alex.client.managed.ui.desktop.ZborDesktopListView;
import ro.alex.client.managed.ui.mobile.ZborMobileDetailsView;
import ro.alex.client.managed.ui.mobile.ZborMobileEditView;
import ro.alex.client.proxy.AvionProxy;
import ro.alex.client.proxy.OrasProxy;
import ro.alex.client.proxy.ZborProxy;
import ro.alex.client.request.ZborRequest;
import ro.alex.client.scaffold.ScaffoldApp;
import ro.alex.client.scaffold.place.ProxyPlace;

public abstract class ZborActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory factory;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        ZborDesktopEditView.instance().setCreating(true);
        Activity activity = new ZborEditActivity(null, factory, ScaffoldApp.isMobile() ? ZborMobileEditView.instance() : ZborDesktopEditView.instance(), placeController);
        return new ZborEditActivityWrapper(factory, ScaffoldApp.isMobile() ? ZborMobileEditView.instance() : ZborDesktopEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<ZborProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<ZborProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        ZborDesktopEditView.instance().setCreating(false);
        EntityProxyId<ZborProxy> proxyId = coerceId(place);
        Activity activity = new ZborEditActivity(proxyId, factory, ScaffoldApp.isMobile() ? ZborMobileEditView.instance() : ZborDesktopEditView.instance(), placeController);
        return new ZborEditActivityWrapper(factory, ScaffoldApp.isMobile() ? ZborMobileEditView.instance() : ZborDesktopEditView.instance(), activity, proxyId);
    }
}
