// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ro.alex.client.managed.activity;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.place.shared.Place;
import com.google.gwt.user.client.ui.AcceptsOneWidget;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.Receiver;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import ro.alex.client.managed.activity.ZborEditActivityWrapper.View;
import ro.alex.client.managed.request.ApplicationRequestFactory;
import ro.alex.client.managed.ui.ZborEditView;
import ro.alex.client.proxy.AvionProxy;
import ro.alex.client.proxy.OrasProxy;
import ro.alex.client.proxy.ZborProxy;
import ro.alex.client.scaffold.activity.IsScaffoldMobileActivity;
import ro.alex.client.scaffold.place.ProxyEditView;
import ro.alex.client.scaffold.place.ProxyListPlace;
import ro.alex.client.scaffold.place.ProxyPlace;

public abstract class ZborEditActivityWrapper_Roo_Gwt implements Activity, IsScaffoldMobileActivity {

    protected Activity wrapped;

    protected View<?> view;

    protected ApplicationRequestFactory requests;

    @Override
    public void start(AcceptsOneWidget display, EventBus eventBus) {
        view.setAvionPickerValues(Collections.<AvionProxy>emptyList());
        requests.avionRequest().findAvionEntries(0, 50).with(ro.alex.client.managed.ui.renderer.AvionProxyRenderer.instance().getPaths()).fire(new Receiver<List<AvionProxy>>() {

            public void onSuccess(List<AvionProxy> response) {
                List<AvionProxy> values = new ArrayList<AvionProxy>();
                values.add(null);
                values.addAll(response);
                view.setAvionPickerValues(values);
            }
        });
        view.setOraspPickerValues(Collections.<OrasProxy>emptyList());
        requests.orasRequest().findOrasEntries(0, 50).with(ro.alex.client.managed.ui.renderer.OrasProxyRenderer.instance().getPaths()).fire(new Receiver<List<OrasProxy>>() {

            public void onSuccess(List<OrasProxy> response) {
                List<OrasProxy> values = new ArrayList<OrasProxy>();
                values.add(null);
                values.addAll(response);
                view.setOraspPickerValues(values);
            }
        });
        view.setOrasdPickerValues(Collections.<OrasProxy>emptyList());
        requests.orasRequest().findOrasEntries(0, 50).with(ro.alex.client.managed.ui.renderer.OrasProxyRenderer.instance().getPaths()).fire(new Receiver<List<OrasProxy>>() {

            public void onSuccess(List<OrasProxy> response) {
                List<OrasProxy> values = new ArrayList<OrasProxy>();
                values.add(null);
                values.addAll(response);
                view.setOrasdPickerValues(values);
            }
        });
        wrapped.start(display, eventBus);
    }

    public interface View_Roo_Gwt<V extends ro.alex.client.managed.ui.ZborEditView<V>> extends ZborEditView<V> {

        void setAvionPickerValues(Collection<AvionProxy> values);

        void setOraspPickerValues(Collection<OrasProxy> values);

        void setOrasdPickerValues(Collection<OrasProxy> values);
    }
}
