// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ro.alex.server.model;

import ro.alex.server.model.Aeroport;

privileged aspect Aeroport_Roo_JavaBean {
    
    public String Aeroport.getDenumire() {
        return this.denumire;
    }
    
    public void Aeroport.setDenumire(String denumire) {
        this.denumire = denumire;
    }
    
}
