// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ro.alex.server.model;

import org.springframework.beans.factory.annotation.Configurable;
import ro.alex.server.model.Clasa;

privileged aspect Clasa_Roo_Configurable {
    
    declare @type: Clasa: @Configurable;
    
}
