// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ro.alex.server.model;

import ro.alex.server.model.Oras;

privileged aspect Oras_Roo_JavaBean {
    
    public String Oras.getDenumire() {
        return this.denumire;
    }
    
    public void Oras.setDenumire(String denumire) {
        this.denumire = denumire;
    }
    
}
