// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ro.alex.client.managed.ui.mobile;
import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.Element;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import ro.alex.client.managed.ui.LocDetailsView;
import ro.alex.client.proxy.AvionProxy;
import ro.alex.client.proxy.ClasaProxy;
import ro.alex.client.proxy.LocProxy;
import ro.alex.client.proxy.ZborProxy;

public abstract class LocMobileDetailsView_Roo_Gwt extends Composite implements LocDetailsView {

    @UiField
    Element id;

    @UiField
    Element numar;

    @UiField
    Element clasa;

    @UiField
    Element avion;

    @UiField
    Element zbor;

    @UiField
    Element ocupat;

    @UiField
    Element version;

    LocProxy proxy;

    public void setValue(LocProxy proxy) {
        this.proxy = proxy;
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        numar.setInnerText(proxy.getNumar() == null ? "" : String.valueOf(proxy.getNumar()));
        clasa.setInnerText(proxy.getClasa() == null ? "" : ro.alex.client.managed.ui.renderer.ClasaProxyRenderer.instance().render(proxy.getClasa()));
        avion.setInnerText(proxy.getAvion() == null ? "" : ro.alex.client.managed.ui.renderer.AvionProxyRenderer.instance().render(proxy.getAvion()));
        zbor.setInnerText(proxy.getZbor() == null ? "" : ro.alex.client.managed.ui.renderer.ZborProxyRenderer.instance().render(proxy.getZbor()));
        ocupat.setInnerText(proxy.getOcupat() == null ? "" : String.valueOf(proxy.getOcupat()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
    }
}
