// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ro.alex.client.managed.ui.mobile;
import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.DivElement;
import com.google.gwt.dom.client.Element;
import com.google.gwt.dom.client.Style.Display;
import com.google.gwt.editor.client.EditorError;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.safehtml.shared.SafeHtmlBuilder;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.CheckBox;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.DoubleBox;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.IntegerBox;
import com.google.gwt.user.client.ui.LongBox;
import com.google.gwt.user.client.ui.TextBox;
import com.google.gwt.user.client.ui.ValueListBox;
import com.google.gwt.user.datepicker.client.DateBox;
import com.google.web.bindery.requestfactory.gwt.client.RequestFactoryEditorDriver;
import com.google.web.bindery.requestfactory.shared.RequestFactory;
import java.util.Collection;
import java.util.List;
import ro.alex.client.managed.activity.LocEditActivityWrapper;
import ro.alex.client.managed.activity.LocEditActivityWrapper.View;
import ro.alex.client.managed.ui.LocEditView;
import ro.alex.client.proxy.AvionProxy;
import ro.alex.client.proxy.ClasaProxy;
import ro.alex.client.proxy.LocProxy;
import ro.alex.client.proxy.ZborProxy;
import ro.alex.client.scaffold.place.ProxyEditView;
import ro.alex.client.scaffold.ui.*;

public abstract class LocMobileEditView_Roo_Gwt extends Composite implements View<LocMobileEditView> {

    @UiField
    IntegerBox numar;

    @UiField(provided = true)
    ValueListBox<ClasaProxy> clasa = new ValueListBox<ClasaProxy>(ro.alex.client.managed.ui.renderer.ClasaProxyRenderer.instance(), new com.google.web.bindery.requestfactory.gwt.ui.client.EntityProxyKeyProvider<ro.alex.client.proxy.ClasaProxy>());

    @UiField(provided = true)
    ValueListBox<AvionProxy> avion = new ValueListBox<AvionProxy>(ro.alex.client.managed.ui.renderer.AvionProxyRenderer.instance(), new com.google.web.bindery.requestfactory.gwt.ui.client.EntityProxyKeyProvider<ro.alex.client.proxy.AvionProxy>());

    @UiField(provided = true)
    ValueListBox<ZborProxy> zbor = new ValueListBox<ZborProxy>(ro.alex.client.managed.ui.renderer.ZborProxyRenderer.instance(), new com.google.web.bindery.requestfactory.gwt.ui.client.EntityProxyKeyProvider<ro.alex.client.proxy.ZborProxy>());

    @UiField(provided = true)
    CheckBox ocupat = new CheckBox() {

        public void setValue(Boolean value) {
            super.setValue(value == null ? Boolean.FALSE : value);
        }
    };

    public void setZborPickerValues(Collection<ZborProxy> values) {
        zbor.setAcceptableValues(values);
    }

    public void setClasaPickerValues(Collection<ClasaProxy> values) {
        clasa.setAcceptableValues(values);
    }

    public void setAvionPickerValues(Collection<AvionProxy> values) {
        avion.setAcceptableValues(values);
    }
}
