// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ro.alex.client.managed.ui.mobile;
import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.Element;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import ro.alex.client.managed.ui.PersoanaDetailsView;
import ro.alex.client.proxy.AbonamentProxy;
import ro.alex.client.proxy.PersoanaProxy;
import ro.alex.client.proxy.UserProxy;

public abstract class PersoanaMobileDetailsView_Roo_Gwt extends Composite implements PersoanaDetailsView {

    @UiField
    Element id;

    @UiField
    Element nume;

    @UiField
    Element prenume;

    @UiField
    Element adresa;

    @UiField
    Element user;

    @UiField
    Element abonament;

    @UiField
    Element version;

    PersoanaProxy proxy;

    public void setValue(PersoanaProxy proxy) {
        this.proxy = proxy;
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        nume.setInnerText(proxy.getNume() == null ? "" : String.valueOf(proxy.getNume()));
        prenume.setInnerText(proxy.getPrenume() == null ? "" : String.valueOf(proxy.getPrenume()));
        adresa.setInnerText(proxy.getAdresa() == null ? "" : String.valueOf(proxy.getAdresa()));
        user.setInnerText(proxy.getUser() == null ? "" : ro.alex.client.managed.ui.renderer.UserProxyRenderer.instance().render(proxy.getUser()));
        abonament.setInnerText(proxy.getAbonament() == null ? "" : ro.alex.client.managed.ui.renderer.AbonamentProxyRenderer.instance().render(proxy.getAbonament()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
    }
}
