// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ro.alex.client.managed.ui.mobile;
import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.Element;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import ro.alex.client.managed.ui.RezervareDetailsView;
import ro.alex.client.proxy.LocProxy;
import ro.alex.client.proxy.PersoanaProxy;
import ro.alex.client.proxy.RezervareProxy;
import ro.alex.client.proxy.ZborProxy;

public abstract class RezervareMobileDetailsView_Roo_Gwt extends Composite implements RezervareDetailsView {

    @UiField
    Element id;

    @UiField
    Element cost;

    @UiField
    Element locDus;

    @UiField
    Element locIntors;

    @UiField
    Element nume;

    @UiField
    Element prenume;

    @UiField
    Element cod;

    @UiField
    Element zborDus;

    @UiField
    Element zborIntors;

    @UiField
    Element persoana;

    @UiField
    Element dusIntors;

    @UiField
    Element version;

    RezervareProxy proxy;

    public void setValue(RezervareProxy proxy) {
        this.proxy = proxy;
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        cost.setInnerText(proxy.getCost() == null ? "" : String.valueOf(proxy.getCost()));
        locDus.setInnerText(proxy.getLocDus() == null ? "" : ro.alex.client.managed.ui.renderer.LocProxyRenderer.instance().render(proxy.getLocDus()));
        locIntors.setInnerText(proxy.getLocIntors() == null ? "" : ro.alex.client.managed.ui.renderer.LocProxyRenderer.instance().render(proxy.getLocIntors()));
        nume.setInnerText(proxy.getNume() == null ? "" : String.valueOf(proxy.getNume()));
        prenume.setInnerText(proxy.getPrenume() == null ? "" : String.valueOf(proxy.getPrenume()));
        cod.setInnerText(proxy.getCod() == null ? "" : String.valueOf(proxy.getCod()));
        zborDus.setInnerText(proxy.getZborDus() == null ? "" : ro.alex.client.managed.ui.renderer.ZborProxyRenderer.instance().render(proxy.getZborDus()));
        zborIntors.setInnerText(proxy.getZborIntors() == null ? "" : ro.alex.client.managed.ui.renderer.ZborProxyRenderer.instance().render(proxy.getZborIntors()));
        persoana.setInnerText(proxy.getPersoana() == null ? "" : ro.alex.client.managed.ui.renderer.PersoanaProxyRenderer.instance().render(proxy.getPersoana()));
        dusIntors.setInnerText(proxy.getDusIntors() == null ? "" : String.valueOf(proxy.getDusIntors()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
    }
}
