// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ro.alex.client.managed.ui.mobile;
import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.DivElement;
import com.google.gwt.dom.client.Element;
import com.google.gwt.dom.client.Style.Display;
import com.google.gwt.editor.client.EditorError;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.safehtml.shared.SafeHtmlBuilder;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.CheckBox;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.DoubleBox;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.IntegerBox;
import com.google.gwt.user.client.ui.LongBox;
import com.google.gwt.user.client.ui.TextBox;
import com.google.gwt.user.client.ui.ValueListBox;
import com.google.gwt.user.datepicker.client.DateBox;
import com.google.web.bindery.requestfactory.gwt.client.RequestFactoryEditorDriver;
import com.google.web.bindery.requestfactory.shared.RequestFactory;
import java.util.Collection;
import java.util.List;
import ro.alex.client.managed.activity.RezervareEditActivityWrapper;
import ro.alex.client.managed.activity.RezervareEditActivityWrapper.View;
import ro.alex.client.managed.ui.RezervareEditView;
import ro.alex.client.proxy.LocProxy;
import ro.alex.client.proxy.PersoanaProxy;
import ro.alex.client.proxy.RezervareProxy;
import ro.alex.client.proxy.ZborProxy;
import ro.alex.client.scaffold.place.ProxyEditView;
import ro.alex.client.scaffold.ui.*;

public abstract class RezervareMobileEditView_Roo_Gwt extends Composite implements View<RezervareMobileEditView> {

    @UiField
    DoubleBox cost;

    @UiField(provided = true)
    ValueListBox<LocProxy> locDus = new ValueListBox<LocProxy>(ro.alex.client.managed.ui.renderer.LocProxyRenderer.instance(), new com.google.web.bindery.requestfactory.gwt.ui.client.EntityProxyKeyProvider<ro.alex.client.proxy.LocProxy>());

    @UiField(provided = true)
    ValueListBox<LocProxy> locIntors = new ValueListBox<LocProxy>(ro.alex.client.managed.ui.renderer.LocProxyRenderer.instance(), new com.google.web.bindery.requestfactory.gwt.ui.client.EntityProxyKeyProvider<ro.alex.client.proxy.LocProxy>());

    @UiField
    TextBox nume;

    @UiField
    TextBox prenume;

    @UiField
    TextBox cod;

    @UiField(provided = true)
    ValueListBox<ZborProxy> zborDus = new ValueListBox<ZborProxy>(ro.alex.client.managed.ui.renderer.ZborProxyRenderer.instance(), new com.google.web.bindery.requestfactory.gwt.ui.client.EntityProxyKeyProvider<ro.alex.client.proxy.ZborProxy>());

    @UiField(provided = true)
    ValueListBox<ZborProxy> zborIntors = new ValueListBox<ZborProxy>(ro.alex.client.managed.ui.renderer.ZborProxyRenderer.instance(), new com.google.web.bindery.requestfactory.gwt.ui.client.EntityProxyKeyProvider<ro.alex.client.proxy.ZborProxy>());

    @UiField(provided = true)
    ValueListBox<PersoanaProxy> persoana = new ValueListBox<PersoanaProxy>(ro.alex.client.managed.ui.renderer.PersoanaProxyRenderer.instance(), new com.google.web.bindery.requestfactory.gwt.ui.client.EntityProxyKeyProvider<ro.alex.client.proxy.PersoanaProxy>());

    @UiField(provided = true)
    CheckBox dusIntors = new CheckBox() {

        public void setValue(Boolean value) {
            super.setValue(value == null ? Boolean.FALSE : value);
        }
    };

    public void setZborDusPickerValues(Collection<ZborProxy> values) {
        zborDus.setAcceptableValues(values);
    }

    public void setZborIntorsPickerValues(Collection<ZborProxy> values) {
        zborIntors.setAcceptableValues(values);
    }

    public void setLocDusPickerValues(Collection<LocProxy> values) {
        locDus.setAcceptableValues(values);
    }

    public void setLocIntorsPickerValues(Collection<LocProxy> values) {
        locIntors.setAcceptableValues(values);
    }

    public void setPersoanaPickerValues(Collection<PersoanaProxy> values) {
        persoana.setAcceptableValues(values);
    }
}
