// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ro.alex.server.model;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import ro.alex.server.model.Rezervare;
import ro.alex.server.model.RezervareDataOnDemand;
import ro.alex.server.model.RezervareIntegrationTest;

privileged aspect RezervareIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RezervareIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RezervareIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: RezervareIntegrationTest: @Transactional;
    
    @Autowired
    RezervareDataOnDemand RezervareIntegrationTest.dod;
    
    @Test
    public void RezervareIntegrationTest.testCountRezervares() {
        Assert.assertNotNull("Data on demand for 'Rezervare' failed to initialize correctly", dod.getRandomRezervare());
        long count = Rezervare.countRezervares();
        Assert.assertTrue("Counter for 'Rezervare' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RezervareIntegrationTest.testFindRezervare() {
        Rezervare obj = dod.getRandomRezervare();
        Assert.assertNotNull("Data on demand for 'Rezervare' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Rezervare' failed to provide an identifier", id);
        obj = Rezervare.findRezervare(id);
        Assert.assertNotNull("Find method for 'Rezervare' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Rezervare' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RezervareIntegrationTest.testFindAllRezervares() {
        Assert.assertNotNull("Data on demand for 'Rezervare' failed to initialize correctly", dod.getRandomRezervare());
        long count = Rezervare.countRezervares();
        Assert.assertTrue("Too expensive to perform a find all test for 'Rezervare', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Rezervare> result = Rezervare.findAllRezervares();
        Assert.assertNotNull("Find all method for 'Rezervare' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Rezervare' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RezervareIntegrationTest.testFindRezervareEntries() {
        Assert.assertNotNull("Data on demand for 'Rezervare' failed to initialize correctly", dod.getRandomRezervare());
        long count = Rezervare.countRezervares();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Rezervare> result = Rezervare.findRezervareEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Rezervare' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Rezervare' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RezervareIntegrationTest.testFlush() {
        Rezervare obj = dod.getRandomRezervare();
        Assert.assertNotNull("Data on demand for 'Rezervare' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Rezervare' failed to provide an identifier", id);
        obj = Rezervare.findRezervare(id);
        Assert.assertNotNull("Find method for 'Rezervare' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRezervare(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Rezervare' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RezervareIntegrationTest.testMergeUpdate() {
        Rezervare obj = dod.getRandomRezervare();
        Assert.assertNotNull("Data on demand for 'Rezervare' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Rezervare' failed to provide an identifier", id);
        obj = Rezervare.findRezervare(id);
        boolean modified =  dod.modifyRezervare(obj);
        Integer currentVersion = obj.getVersion();
        Rezervare merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Rezervare' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RezervareIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Rezervare' failed to initialize correctly", dod.getRandomRezervare());
        Rezervare obj = dod.getNewTransientRezervare(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Rezervare' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Rezervare' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Rezervare' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RezervareIntegrationTest.testRemove() {
        Rezervare obj = dod.getRandomRezervare();
        Assert.assertNotNull("Data on demand for 'Rezervare' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Rezervare' failed to provide an identifier", id);
        obj = Rezervare.findRezervare(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Rezervare' with identifier '" + id + "'", Rezervare.findRezervare(id));
    }
    
}
