// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ro.alex.server.model;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import ro.alex.server.model.Zbor;
import ro.alex.server.model.ZborDataOnDemand;
import ro.alex.server.model.ZborIntegrationTest;

privileged aspect ZborIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ZborIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ZborIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ZborIntegrationTest: @Transactional;
    
    @Autowired
    ZborDataOnDemand ZborIntegrationTest.dod;
    
    @Test
    public void ZborIntegrationTest.testCountZbors() {
        Assert.assertNotNull("Data on demand for 'Zbor' failed to initialize correctly", dod.getRandomZbor());
        long count = Zbor.countZbors();
        Assert.assertTrue("Counter for 'Zbor' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ZborIntegrationTest.testFindZbor() {
        Zbor obj = dod.getRandomZbor();
        Assert.assertNotNull("Data on demand for 'Zbor' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Zbor' failed to provide an identifier", id);
        obj = Zbor.findZbor(id);
        Assert.assertNotNull("Find method for 'Zbor' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Zbor' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ZborIntegrationTest.testFindAllZbors() {
        Assert.assertNotNull("Data on demand for 'Zbor' failed to initialize correctly", dod.getRandomZbor());
        long count = Zbor.countZbors();
        Assert.assertTrue("Too expensive to perform a find all test for 'Zbor', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Zbor> result = Zbor.findAllZbors();
        Assert.assertNotNull("Find all method for 'Zbor' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Zbor' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ZborIntegrationTest.testFindZborEntries() {
        Assert.assertNotNull("Data on demand for 'Zbor' failed to initialize correctly", dod.getRandomZbor());
        long count = Zbor.countZbors();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Zbor> result = Zbor.findZborEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Zbor' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Zbor' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ZborIntegrationTest.testFlush() {
        Zbor obj = dod.getRandomZbor();
        Assert.assertNotNull("Data on demand for 'Zbor' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Zbor' failed to provide an identifier", id);
        obj = Zbor.findZbor(id);
        Assert.assertNotNull("Find method for 'Zbor' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyZbor(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Zbor' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ZborIntegrationTest.testMergeUpdate() {
        Zbor obj = dod.getRandomZbor();
        Assert.assertNotNull("Data on demand for 'Zbor' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Zbor' failed to provide an identifier", id);
        obj = Zbor.findZbor(id);
        boolean modified =  dod.modifyZbor(obj);
        Integer currentVersion = obj.getVersion();
        Zbor merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Zbor' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ZborIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Zbor' failed to initialize correctly", dod.getRandomZbor());
        Zbor obj = dod.getNewTransientZbor(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Zbor' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Zbor' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Zbor' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ZborIntegrationTest.testRemove() {
        Zbor obj = dod.getRandomZbor();
        Assert.assertNotNull("Data on demand for 'Zbor' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Zbor' failed to provide an identifier", id);
        obj = Zbor.findZbor(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Zbor' with identifier '" + id + "'", Zbor.findZbor(id));
    }
    
}
