// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ro.alex.client.managed.ui.renderer;
import com.google.gwt.text.shared.AbstractRenderer;
import ro.alex.client.managed.request.ApplicationEntityTypesProcessor;
import ro.alex.client.proxy.AbonamentProxy;
import ro.alex.client.proxy.AeroportProxy;
import ro.alex.client.proxy.AvionProxy;
import ro.alex.client.proxy.ClasaProxy;
import ro.alex.client.proxy.CompanieProxy;
import ro.alex.client.proxy.ContProxy;
import ro.alex.client.proxy.LocProxy;
import ro.alex.client.proxy.OrasProxy;
import ro.alex.client.proxy.PersoanaProxy;
import ro.alex.client.proxy.RezervareProxy;
import ro.alex.client.proxy.UserProxy;
import ro.alex.client.proxy.ZborProxy;
import ro.alex.client.scaffold.place.ProxyListPlace;

public abstract class ApplicationListPlaceRenderer_Roo_Gwt extends AbstractRenderer<ProxyListPlace> {

    public String render(ProxyListPlace object) {
        return new ApplicationEntityTypesProcessor<String>() {

            @Override
            public void handleAbonament(AbonamentProxy isNull) {
                setResult("Abonaments");
            }

            @Override
            public void handleAeroport(AeroportProxy isNull) {
                setResult("Aeroports");
            }

            @Override
            public void handleAvion(AvionProxy isNull) {
                setResult("Avions");
            }

            @Override
            public void handleClasa(ClasaProxy isNull) {
                setResult("Clasas");
            }

            @Override
            public void handleCompanie(CompanieProxy isNull) {
                setResult("Companies");
            }

            @Override
            public void handleCont(ContProxy isNull) {
                setResult("Conts");
            }

            @Override
            public void handleLoc(LocProxy isNull) {
                setResult("Locs");
            }

            @Override
            public void handleOras(OrasProxy isNull) {
                setResult("Orass");
            }

            @Override
            public void handlePersoana(PersoanaProxy isNull) {
                setResult("Persoanas");
            }

            @Override
            public void handleRezervare(RezervareProxy isNull) {
                setResult("Rezervares");
            }

            @Override
            public void handleUser(UserProxy isNull) {
                setResult("Users");
            }

            @Override
            public void handleZbor(ZborProxy isNull) {
                setResult("Zbors");
            }
        }.process(object.getProxyClass());
    }
}
